package view;

import javax.swing.JPanel;
import javax.swing.JWindow;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;

import javax.swing.JLabel;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.Font;

/**
 * Class for managing alerts
 */
public class Alert implements ActionListener{

	/**
	 * Window that appears in case of error or other events
	 */
	private JWindow alert;
	/**
	 * Reference to the frame, for managing JWindow position
	 */
	private JFrame f;
	/**
	 * Icon in the alert
	 */
	private String icon;
	/*
	 * Text in the alert
	 */
	private String text;
	/**
	 * Background color
	 */
	private Color background_color = Color.decode("#ffffff");
	/**
	 * font
	 */
	private String font = "SansSerif";
	/**
	 * button OK, to close alert
	 */
	private JButton btn_ok = new JButton("OK");

	/**
	 * It creates the alert
	 * 
	 * @param f reference to the frame
	 * @param text text to put in the alert
	 * @param icon icon to put in the alert
	 */
	public Alert(JFrame f, String text, String icon)
	{
		alert = new JWindow(f);
		alert.setVisible(true);

		this.f=f;
		this.text=text;
		this.icon=icon;

		btn_ok.addActionListener(this);
	}

	/**
	 * It shows a new alert (for errors or other events)
	 */
	public void showAlert()
	{
		// panel
		JPanel panel = new JPanel(new GridBagLayout());
		panel.setBorder(BorderFactory.createLineBorder(Color.black,2));
		panel.setBackground(background_color);
		panel.setSize(250,250);
		GridBagConstraints gbc = new GridBagConstraints();
		alert.add(panel);
		// icon
		JLabel l_icon = new JLabel();
		l_icon.setIcon(new ImageIcon(System.getProperty("user.dir") + "\\res\\img\\" + icon));
		l_icon.setBorder(BorderFactory.createLineBorder(background_color,20));
		gbc.weighty = 1;
		gbc.anchor = GridBagConstraints.NORTH;
		gbc.gridx = 0;
		gbc.gridy = 1;
		panel.add(l_icon, gbc);
		// text
		JLabel l_text = new JLabel("<html>"+text+"</html>");
		l_text.setFont(new Font(font, Font.BOLD, 15));
		gbc.gridx = 0;
		gbc.gridy = 2;
		panel.add(l_text, gbc);
		//button OK
		setButton(btn_ok, Color.decode("#fc3259"));
		gbc.ipadx = 100;
		gbc.ipady = 10;
		gbc.gridx = 0;
		gbc.gridy = 3;
		panel.add(btn_ok, gbc);

		alert.setSize(250,300);
		alert.setLocationRelativeTo(f);

		f.setEnabled(false);
	}

	/**
	 * It adds style to buttons
	 * 
	 * @param btn button to customize
	 * @param color color to use for the background of the button 
	 */
	public void setButton(JButton btn, Color color)
	{
		btn.setPreferredSize(new Dimension(100,20));
		btn.setForeground(background_color);
		btn.setFont(new Font(font, Font.BOLD, 15));
		btn.setBackground(color);
		btn.setBorder(BorderFactory.createLineBorder(color));
		btn.setFocusable(false);
	}

	// debug
	// public static void main(String[] args) {
	// 	JFrame f = new JFrame();
	// 	f.setSize(250, 250);
	// 	f.setVisible(true);
	// 	//new Alert(f,"Information","info.png").showConfirmAlert(new Semaphore(1));
	// 	//Alert a = new Alert(f,"error information","error.png");
	// }

	/**
	 * It manages events generated by JButton objects
	 */
	@Override
	public void actionPerformed(ActionEvent e) 
	{
		// button ok
		if(e.getSource() == btn_ok)
		{
			// close alert and enable frame
			alert.setVisible(false);
			alert.dispose();
			f.setEnabled(true);
		}	
	}
	

}
